# Generated by Django 5.1 on 2024-08-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('dimensions', models.CharField(max_length=50)),
                ('pros', models.CharField(max_length=500)),
                ('cons', models.CharField(max_length=500)),
                ('reviews', models.CharField(max_length=500)),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
